# Generated by Django 3.2.9 on 2021-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='card_content',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
