# Generated by Django 3.2.9 on 2021-12-24 17:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211219_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
